// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_reserva_Futbol_Ya.Data;

#nullable disable

namespace Sistema_de_reserva_Futbol_Ya.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251030203654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Cancha", b =>
                {
                    b.Property<int>("CodigoCancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoCancha"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("CodigoCancha");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Material_Deportivo", b =>
                {
                    b.Property<int>("CodigoMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoMaterial"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoMaterial");

                    b.ToTable("MaterialesDeportivos");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Producto", b =>
                {
                    b.Property<int>("CodigoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProducto"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Tipo")
                        .HasColumnType("bit");

                    b.HasKey("CodigoProducto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Reserva", b =>
                {
                    b.Property<int>("CodigoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoReserva"));

                    b.Property<int>("CodigoCancha")
                        .HasColumnType("int");

                    b.Property<int>("CodigoUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.HasKey("CodigoReserva");

                    b.HasIndex("CodigoCancha");

                    b.HasIndex("CodigoUsuario");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Reserva_Material", b =>
                {
                    b.Property<int>("CodigoReservaMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoReservaMaterial"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CodigoMaterial")
                        .HasColumnType("int");

                    b.Property<int>("CodigoReserva")
                        .HasColumnType("int");

                    b.HasKey("CodigoReservaMaterial");

                    b.HasIndex("CodigoMaterial");

                    b.HasIndex("CodigoReserva");

                    b.ToTable("ReservaMateriales");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Usuario", b =>
                {
                    b.Property<int>("CodigoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CambiarContraseña")
                        .HasColumnType("bit");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rol")
                        .HasColumnType("bit");

                    b.HasKey("CodigoUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Venta", b =>
                {
                    b.Property<int>("CodigoVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoVenta"));

                    b.Property<int>("CodigoUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraVenta")
                        .HasColumnType("time");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodigoVenta");

                    b.HasIndex("CodigoUsuario");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Venta_Detallada", b =>
                {
                    b.Property<int>("CodigoVentaDetallada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoVentaDetallada"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CodigoProducto")
                        .HasColumnType("int");

                    b.Property<int>("CodigoVenta")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodigoVentaDetallada");

                    b.HasIndex("CodigoProducto");

                    b.HasIndex("CodigoVenta");

                    b.ToTable("VentasDetalladas");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Reserva", b =>
                {
                    b.HasOne("Sistema_de_reserva_Futbol_Ya.Models.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("CodigoCancha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_de_reserva_Futbol_Ya.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("CodigoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Reserva_Material", b =>
                {
                    b.HasOne("Sistema_de_reserva_Futbol_Ya.Models.Material_Deportivo", "Material_Deportivo")
                        .WithMany("Reserva_Materiales")
                        .HasForeignKey("CodigoMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_de_reserva_Futbol_Ya.Models.Reserva", "Reserva")
                        .WithMany("Reserva_Materiales")
                        .HasForeignKey("CodigoReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material_Deportivo");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Venta", b =>
                {
                    b.HasOne("Sistema_de_reserva_Futbol_Ya.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("CodigoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Venta_Detallada", b =>
                {
                    b.HasOne("Sistema_de_reserva_Futbol_Ya.Models.Producto", "Producto")
                        .WithMany("VentasDetalladas")
                        .HasForeignKey("CodigoProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_de_reserva_Futbol_Ya.Models.Venta", "Venta")
                        .WithMany("Venta_Detalladas")
                        .HasForeignKey("CodigoVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Cancha", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Material_Deportivo", b =>
                {
                    b.Navigation("Reserva_Materiales");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Producto", b =>
                {
                    b.Navigation("VentasDetalladas");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Reserva", b =>
                {
                    b.Navigation("Reserva_Materiales");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Sistema_de_reserva_Futbol_Ya.Models.Venta", b =>
                {
                    b.Navigation("Venta_Detalladas");
                });
#pragma warning restore 612, 618
        }
    }
}
