// <auto-generated />
using System;
using FutbolyaAPIS.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutbolyaAPIS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615005755_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Cancha", b =>
                {
                    b.Property<int>("Cod_Cancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Cancha"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Cod_Cancha");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.HorarioDisponible", b =>
                {
                    b.Property<int>("Cod_Horario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Horario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("Cod_Horario");

                    b.ToTable("HorariosDisponibles");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Material_Deportivo", b =>
                {
                    b.Property<int>("Cod_Material")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Material"));

                    b.Property<int>("Cant_Material")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cod_Material");

                    b.ToTable("MaterialesDeportivos");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Producto", b =>
                {
                    b.Property<int>("Cod_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Producto"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Cod_Producto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Reserva", b =>
                {
                    b.Property<int>("Cod_Reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Reserva"));

                    b.Property<int>("Cod_Cancha")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Horario")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Dni_Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefono_Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cod_Reserva");

                    b.HasIndex("Cod_Cancha");

                    b.HasIndex("Cod_Horario");

                    b.HasIndex("Cod_Usuario");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Reserva_Material", b =>
                {
                    b.Property<int>("Cod_Reserva_Mat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Reserva_Mat"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Material")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Reserva")
                        .HasColumnType("int");

                    b.HasKey("Cod_Reserva_Mat");

                    b.HasIndex("Cod_Material");

                    b.HasIndex("Cod_Reserva");

                    b.ToTable("ReservasMateriales");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Usuario", b =>
                {
                    b.Property<int>("Cod_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Usuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cambiar_Contraseña")
                        .HasColumnType("bit");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rol")
                        .HasColumnType("bit");

                    b.HasKey("Cod_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Venta", b =>
                {
                    b.Property<int>("Cod_Venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Venta"));

                    b.Property<int>("Cod_Usuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Cod_Venta");

                    b.HasIndex("Cod_Usuario");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.VentaDetallada", b =>
                {
                    b.Property<int>("Cod_Venta_Detallada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Venta_Detallada"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Producto")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Venta")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Cod_Venta_Detallada");

                    b.HasIndex("Cod_Producto");

                    b.HasIndex("Cod_Venta");

                    b.ToTable("VentasDetalladas");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Reserva", b =>
                {
                    b.HasOne("FutbolyaAPIS.Entidades.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("Cod_Cancha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutbolyaAPIS.Entidades.HorarioDisponible", "HorarioDisponible")
                        .WithMany("Reservas")
                        .HasForeignKey("Cod_Horario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutbolyaAPIS.Entidades.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("Cod_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("HorarioDisponible");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Reserva_Material", b =>
                {
                    b.HasOne("FutbolyaAPIS.Entidades.Material_Deportivo", "Material_Deportivo")
                        .WithMany("ReservaMateriales")
                        .HasForeignKey("Cod_Material")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutbolyaAPIS.Entidades.Reserva", "Reserva")
                        .WithMany("ReservaMateriales")
                        .HasForeignKey("Cod_Reserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material_Deportivo");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Venta", b =>
                {
                    b.HasOne("FutbolyaAPIS.Entidades.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("Cod_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.VentaDetallada", b =>
                {
                    b.HasOne("FutbolyaAPIS.Entidades.Producto", "Producto")
                        .WithMany("VentasDetalladas")
                        .HasForeignKey("Cod_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutbolyaAPIS.Entidades.Venta", "Venta")
                        .WithMany("VentasDetalladas")
                        .HasForeignKey("Cod_Venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Cancha", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.HorarioDisponible", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Material_Deportivo", b =>
                {
                    b.Navigation("ReservaMateriales");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Producto", b =>
                {
                    b.Navigation("VentasDetalladas");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Reserva", b =>
                {
                    b.Navigation("ReservaMateriales");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Usuario", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("FutbolyaAPIS.Entidades.Venta", b =>
                {
                    b.Navigation("VentasDetalladas");
                });
#pragma warning restore 612, 618
        }
    }
}
