// <auto-generated />
using System;
using FutbolYaAPI.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutbolYaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutbolYaAPI.Entidades.Auditoria", b =>
                {
                    b.Property<int>("Cod_Auditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Auditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Cod_Entidad_Afectada")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Entidad_Afectada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha_Hora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Valor_Anterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor_Nuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cod_Auditoria");

                    b.HasIndex("Cod_Usuario");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Cancha", b =>
                {
                    b.Property<int>("Cod_Cancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Cancha"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Cod_Cancha");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Cancha_Horario", b =>
                {
                    b.Property<int>("Cod_Cancha_Horario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Cancha_Horario"));

                    b.Property<int>("Cod_Cancha")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Horario")
                        .HasColumnType("int");

                    b.HasKey("Cod_Cancha_Horario");

                    b.HasIndex("Cod_Horario");

                    b.HasIndex("Cod_Cancha", "Cod_Horario")
                        .IsUnique();

                    b.ToTable("CanchaHorarios");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.HorarioDisponible", b =>
                {
                    b.Property<int>("Cod_Horario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Horario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("Cod_Horario");

                    b.ToTable("HorariosDisponibles");

                    b.HasData(
                        new
                        {
                            Cod_Horario = 1,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 1, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 2,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 2, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 1, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 3,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 3, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 4,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 4, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 3, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 5,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 5, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 4, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 6,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 6, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 5, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 7,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 7, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 8,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 8, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 9,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 9, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 10,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 10, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 11,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 11, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 12,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 12, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 13,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 13, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 14,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 14, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 15,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 15, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 16,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 16, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 17,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 17, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 18,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 18, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 19,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 19, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 20,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 20, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 21,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 21, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 20, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 22,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 22, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 21, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 23,
                            Activo = true,
                            HoraFin = new TimeSpan(0, 23, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 22, 0, 0, 0)
                        },
                        new
                        {
                            Cod_Horario = 24,
                            Activo = true,
                            HoraFin = new TimeSpan(1, 0, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 23, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Material_Deportivo", b =>
                {
                    b.Property<int>("Cod_Material")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Material"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Cant_Material")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cod_Material");

                    b.ToTable("MaterialesDeportivos");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Producto", b =>
                {
                    b.Property<int>("Cod_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Producto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Cod_Producto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Reserva", b =>
                {
                    b.Property<int>("Cod_Reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Reserva"));

                    b.Property<int>("Cod_Cancha")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Dni_Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefono_Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cod_Reserva");

                    b.HasIndex("Cod_Cancha");

                    b.HasIndex("Cod_Usuario");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Reserva_Horario", b =>
                {
                    b.Property<int>("Cod_Reserva_Horario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Reserva_Horario"));

                    b.Property<int>("Cod_Horario")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Reserva")
                        .HasColumnType("int");

                    b.HasKey("Cod_Reserva_Horario");

                    b.HasIndex("Cod_Horario");

                    b.HasIndex("Cod_Reserva", "Cod_Horario")
                        .IsUnique();

                    b.ToTable("ReservasHorarios");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Reserva_Material", b =>
                {
                    b.Property<int>("Cod_Reserva_Mat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Reserva_Mat"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Material")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Reserva")
                        .HasColumnType("int");

                    b.HasKey("Cod_Reserva_Mat");

                    b.HasIndex("Cod_Material");

                    b.HasIndex("Cod_Reserva");

                    b.ToTable("ReservasMateriales");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Usuario", b =>
                {
                    b.Property<int>("Cod_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Usuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cambiar_Contraseña")
                        .HasColumnType("bit");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rol")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Token_Expira")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token_Recuperacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cod_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Venta", b =>
                {
                    b.Property<int>("Cod_Venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Venta"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Cod_Usuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Cod_Venta");

                    b.HasIndex("Cod_Usuario");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.VentaDetallada", b =>
                {
                    b.Property<int>("Cod_Venta_Detallada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Venta_Detallada"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Producto")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Venta")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Cod_Venta_Detallada");

                    b.HasIndex("Cod_Producto");

                    b.HasIndex("Cod_Venta");

                    b.ToTable("VentasDetalladas");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Auditoria", b =>
                {
                    b.HasOne("FutbolYaAPI.Entidades.Usuario", "Usuario")
                        .WithMany("RegistrosAuditoria")
                        .HasForeignKey("Cod_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Cancha_Horario", b =>
                {
                    b.HasOne("FutbolYaAPI.Entidades.Cancha", "Cancha")
                        .WithMany("CanchaHorarios")
                        .HasForeignKey("Cod_Cancha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutbolYaAPI.Entidades.HorarioDisponible", "HorarioDisponible")
                        .WithMany("CanchaHorarios")
                        .HasForeignKey("Cod_Horario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("HorarioDisponible");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Reserva", b =>
                {
                    b.HasOne("FutbolYaAPI.Entidades.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("Cod_Cancha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutbolYaAPI.Entidades.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("Cod_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Reserva_Horario", b =>
                {
                    b.HasOne("FutbolYaAPI.Entidades.HorarioDisponible", "HorarioDisponible")
                        .WithMany("ReservaHorarios")
                        .HasForeignKey("Cod_Horario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutbolYaAPI.Entidades.Reserva", "Reserva")
                        .WithMany("ReservaHorarios")
                        .HasForeignKey("Cod_Reserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HorarioDisponible");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Reserva_Material", b =>
                {
                    b.HasOne("FutbolYaAPI.Entidades.Material_Deportivo", "Material_Deportivo")
                        .WithMany("ReservaMateriales")
                        .HasForeignKey("Cod_Material")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutbolYaAPI.Entidades.Reserva", "Reserva")
                        .WithMany("ReservaMateriales")
                        .HasForeignKey("Cod_Reserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material_Deportivo");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Venta", b =>
                {
                    b.HasOne("FutbolYaAPI.Entidades.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("Cod_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.VentaDetallada", b =>
                {
                    b.HasOne("FutbolYaAPI.Entidades.Producto", "Producto")
                        .WithMany("VentasDetalladas")
                        .HasForeignKey("Cod_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutbolYaAPI.Entidades.Venta", "Venta")
                        .WithMany("VentasDetalladas")
                        .HasForeignKey("Cod_Venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Cancha", b =>
                {
                    b.Navigation("CanchaHorarios");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.HorarioDisponible", b =>
                {
                    b.Navigation("CanchaHorarios");

                    b.Navigation("ReservaHorarios");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Material_Deportivo", b =>
                {
                    b.Navigation("ReservaMateriales");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Producto", b =>
                {
                    b.Navigation("VentasDetalladas");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Reserva", b =>
                {
                    b.Navigation("ReservaHorarios");

                    b.Navigation("ReservaMateriales");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Usuario", b =>
                {
                    b.Navigation("RegistrosAuditoria");

                    b.Navigation("Reservas");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("FutbolYaAPI.Entidades.Venta", b =>
                {
                    b.Navigation("VentasDetalladas");
                });
#pragma warning restore 612, 618
        }
    }
}
